name: Daily Toiling

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12,15,17,20,23 * * *"

jobs:
  toil:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Post
        env:
          BLUESKY_USERNAME: ${{ secrets.BLUESKY_USERNAME }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          RUN_COUNT: ${{ github.run_number }}
        run: |
          deno task post
